//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANG_SANPHAM()
        {
            this.BANG_CHITIETHOADON = new HashSet<BANG_CHITIETHOADON>();
            this.BANG_CHITIETHOADON1 = new HashSet<BANG_CHITIETHOADON>();
            this.BANG_CHITIETHOADON2 = new HashSet<BANG_CHITIETHOADON>();
        }
    
        public string idsanpham { get; set; }
        public string idcategory { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string idblock { get; set; }
        public string iddetail { get; set; }
        public string datesell { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual BANG_BLOCK BANG_BLOCK { get; set; }
        public virtual BANG_CATEGORY BANG_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON2 { get; set; }
        public virtual BANG_DETAIL BANG_DETAIL { get; set; }
    }
}
