//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANG_HOADON()
        {
            this.BANG_CHITIETHOADON = new HashSet<BANG_CHITIETHOADON>();
            this.BANG_CHITIETHOADON1 = new HashSet<BANG_CHITIETHOADON>();
            this.BANG_CHITIETHOADON2 = new HashSet<BANG_CHITIETHOADON>();
        }
    
        public string idhoadon { get; set; }
        public string idnhanvien { get; set; }
        public string idkhachhang { get; set; }
        public Nullable<int> tongtien { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public Nullable<int> tongtiencuoi { get; set; }
        public Nullable<int> soluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_CHITIETHOADON> BANG_CHITIETHOADON2 { get; set; }
        public virtual BANG_KHACHHANG BANG_KHACHHANG { get; set; }
        public virtual BANG_NHANVIEN BANG_NHANVIEN { get; set; }
    }
}
