//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_HISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANG_HISTORY()
        {
            this.BANG_NHANVIEN1 = new HashSet<BANG_NHANVIEN>();
        }
    
        public string idhistory { get; set; }
        public string idnhanvien { get; set; }
        public string idkhachhang { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public Nullable<System.DateTime> ngayluukho { get; set; }
        public string chitiet { get; set; }
    
        public virtual BANG_KHACHHANG BANG_KHACHHANG { get; set; }
        public virtual BANG_NHANVIEN BANG_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_NHANVIEN> BANG_NHANVIEN1 { get; set; }
    }
}
