//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANG_KHACHHANG()
        {
            this.BANG_HISTORY = new HashSet<BANG_HISTORY>();
            this.BANG_HOADON = new HashSet<BANG_HOADON>();
        }
    
        public string idkhachhang { get; set; }
        public string name { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public string idkhuyenmai { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<int> Old { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string Chitiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_HISTORY> BANG_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_HOADON> BANG_HOADON { get; set; }
        public virtual BANG_KHUYENMAI BANG_KHUYENMAI { get; set; }
    }
}
