//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_THONGBAO
    {
        public string idthongbao { get; set; }
        public string noidung { get; set; }
        public string tieude { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
