//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_CHITIETHOADON
    {
        public string idhoadon { get; set; }
        public string idsanpham { get; set; }
        public Nullable<int> dongia { get; set; }
    
        public virtual BANG_HOADON BANG_HOADON { get; set; }
        public virtual BANG_HOADON BANG_HOADON1 { get; set; }
        public virtual BANG_SANPHAM BANG_SANPHAM { get; set; }
        public virtual BANG_SANPHAM BANG_SANPHAM1 { get; set; }
        public virtual BANG_HOADON BANG_HOADON2 { get; set; }
        public virtual BANG_SANPHAM BANG_SANPHAM2 { get; set; }
    }
}
