//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_ACCESS_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANG_NHANVIEN()
        {
            this.BANG_HISTORY = new HashSet<BANG_HISTORY>();
            this.BANG_HOADON = new HashSet<BANG_HOADON>();
        }
    
        public string idnhanvien { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<int> phonenumber { get; set; }
        public Nullable<int> idcard { get; set; }
        public string address { get; set; }
        public string idhistorysell { get; set; }
        public string position { get; set; }
        public byte[] avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_HISTORY> BANG_HISTORY { get; set; }
        public virtual BANG_HISTORY BANG_HISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_HOADON> BANG_HOADON { get; set; }
    }
}
